### ISSUE TITLE
[Feature] Use selected hotbar slot when items are added to the hotbar

### ISSUE THREAD

**Issue by SalieriC** [mass8326/vintagestory-nohands#1]
Might be out of scope for this mod but I think it'd like to suggest it anyway because it's also been an annoyance for me (as well as having to open the inventory just to move an item in order to be able to perform a certain action):
Currently the game tries to fill the hotbar from left to right when picking something up or using Shift+LMB to send an item from the backpack to the hotbar. If you want to have something in a specific slot this can be very frustrating and also leads to unnecessary inventory micro-management. I'd prefer if the game would always use the selected hotbar slot instead if a) the slot is empty or has the same item that was picked but and b) there is no other partial stack of the picked up item already in the bar (if the item is stackable).
This should only apply to the above mentioned actions I think as the player does this actively. When picking up drops, the default behaviour should apply I think.

**Comment by mass8326** [comment]
This is something that has started to bother me recently as well, so I'm glad you brought it up!

I'll take a look into it, though I make no promises. This mod was straightforward enough for my limited C# knowledge, but modifying pre-existing behavior might be beyond me.

**Comment by mass8326** [comment]
To give an update, I've been able to get this working for rocks and sticks on the ground!

However, I'd like for it to work for crates, piles, and ground storage too. That'll take me a bit more time to explore and implement.

It looks like this kind of tweak needs to be run on the server, unfortunately, so I'll likely release it as a different mod to keep this one client-side only.

**Comment by mass8326** [comment]
Published the new mod! Thanks for suggesting the idea!
https://mods.vintagestory.at/pickupartist
https://github.com/mass8326/vintagestory-pickupartist
